resources:
  - ../../base

namePrefix: prd-

namespace: seu-projeto-prd

images:
  - name: image-registry.openshift-image-registry.svc:5000/vac-testes/qualificar-partes
    newTag: prd

patches:
  - target:
      kind: Deployment
      name: qualificar-partes
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
