replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/qualificar-partes
  tag: latest
  pullPolicy: Always

service:
  port: 8080

route:
  enabled: true
  host: qualificar-partes.apps.ocp-dev.seudominio.gov.br

env:
  secretName: credenciais-dw
