resources:
  - ../../base

namePrefix: dev-

namespace: seu-projeto-dev

images:
  - name: image-registry.openshift-image-registry.svc:5000/vac-testes/qualificar-partes
    newTag: dev

patches:
  - target:
      kind: Deployment
      name: qualificar-partes
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
